// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLRavFJVJ3T_ZRsH86WNmHP70HSZlruU',
    appId: '1:936640374389:web:b00ba0c57f1917fa2cfa3c',
    messagingSenderId: '936640374389',
    projectId: 'kltn-56ae4',
    authDomain: 'kltn-56ae4.firebaseapp.com',
    storageBucket: 'kltn-56ae4.appspot.com',
    measurementId: 'G-P8MGH4LMES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lmnOR0anpmgF0cGK4VuW19EvxyJia18',
    appId: '1:936640374389:android:35025d73c1f3f8c12cfa3c',
    messagingSenderId: '936640374389',
    projectId: 'kltn-56ae4',
    storageBucket: 'kltn-56ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFAAjvm4t57CwmPtAOS-dJjlTIek41kE',
    appId: '1:936640374389:ios:bbb2c5ddd56c7ddb2cfa3c',
    messagingSenderId: '936640374389',
    projectId: 'kltn-56ae4',
    storageBucket: 'kltn-56ae4.appspot.com',
    iosBundleId: 'com.hungdev.kltnMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFAAjvm4t57CwmPtAOS-dJjlTIek41kE',
    appId: '1:936640374389:ios:bbb2c5ddd56c7ddb2cfa3c',
    messagingSenderId: '936640374389',
    projectId: 'kltn-56ae4',
    storageBucket: 'kltn-56ae4.appspot.com',
    iosBundleId: 'com.hungdev.kltnMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBLRavFJVJ3T_ZRsH86WNmHP70HSZlruU',
    appId: '1:936640374389:web:ddffa1d7cb0471d42cfa3c',
    messagingSenderId: '936640374389',
    projectId: 'kltn-56ae4',
    authDomain: 'kltn-56ae4.firebaseapp.com',
    storageBucket: 'kltn-56ae4.appspot.com',
    measurementId: 'G-BJSS9WMYEZ',
  );
}
